<?php
$pb_strings = array(
	"WELCOME_MSG" => "Welcome to the SugarCRM Package Builder!",
	"PATH_TO_REPO_MSG" => "Please enter the path to your git repository: ",
	"PATH_TO_REPO_ERROR" => "[ERROR] Please verify the path to your git repository and run the application again.",
	"PATH_TO_REPO_INVALID" => "The path entered is not a git repository.",
	"PATH_TO_REPO_SUCCESS" => "Git repository found!",
	"OPTION_MSG" => "What would you like to do?",
	"OPTION_1_MSG" => "  [1] Create package from release branch.",
	"OPTION_2_MSG" => "  [2] Create package from tagged versions on master branch.",
	"OPTION_3_MSG" => "  [3] Exit application.",
	"OPTION_SELECT_MSG" => "Select Option: ",
	"EXIT_MSG" => "Goodbye!",
	"INVALID_OPTION_MSG" => "Invalid option",
	"GIT_MASTER_OUT_OF_SYNC_ERROR" => "[ERROR] The master branch working directory is not clean.\nPlease resolve this before running Package Builder again.",
	"GIT_CONFIG_SET_EMAIL_ERROR" => "[ERROR] Please set user.email in your git config and rerun Package Builder.",
	"GIT_CONFIG_SET_NAME_ERROR" => "[ERROR] Please set user.name in your git config and rerun Package Builder.",
	"GIT_RELEASE_PREFIX" => "release-",
	"GIT_SELECT_RELEASE_MSG" => "Please select the release you would like to use: ",
	"GIT_NO_RELEASE_ERROR" => "[ERROR] There were no release branches found in the remote repository.\nIf the release branch exists locally please push it to the remote repository.",
	"GIT_MERGE_NOW_MSG" => "Would you like to merge the release branch with master now [Y/n]? ",
	"GIT_TAG_NOTIFY_MSG" => "Tagging master branch: v",
	"GIT_PUSH_NOW_MSG" => "Would you like to push to remote repository now [Y/n]? ",
	"GIT_DELETE_REL_BRANCH_NOW_MSG" => "Would you like to delete the release branch now [Y/n]?",
	"GIT_SELECT_REL_VERSION" => "Please select the new release version:",
	"GIT_SELECT_CUR_VERSION" => "Please select the current production version:",
	"CURRENT_VERSION_LABEL" => "Current Version: ",
	"RELEASE_VERSION_LABEL" => "Release Version: ",
	"CREATE_NEW_BUILD_MSG" => "Would you like to create a new build from these versions [Y/n]? ",
);
?>